CHUNK_OVERLAP: 50
CHUNK_SIZE: 500
DATA_PATH: data/llama_alz_sss
DB_FAISS_PATH: vectorstore/llama_alz_sss
EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
MAX_NEW_TOKENS: 256
MODEL_BIN_PATH: models/llama-2-13b-chat.ggmlv3.q4_0.bin
MODEL_TYPE: llama
OPENAI_API_KEY: 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
TEMPERATURE: 0.01
VECTOR_COUNT: 2
