CHUNK_OVERLAP: 50
CHUNK_SIZE: 500
DATA_PATH: data/gpt_alz_sss
DB_FAISS_PATH: vectorstore/gpt_alz_sss
EMBEDDING_MODEL: OpenAI/text-embedding-ada-002
MAX_NEW_TOKENS: 256
MODEL_BIN_PATH: models/llama-2-7b-chat.ggmlv3.q8_0.bin
MODEL_TYPE: openai
OPENAI_API_KEY: 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
RETURN_SOURCE_DOCUMENTS: true
TEMPERATURE: 0.01
VECTOR_COUNT: 2
